Repository imDarshanGK/SmartStudyBot, pull requests merged in 2025-07, with the labels that each got.

#11 Input prompt continues until proper subject selected
  modules/__init__.py
  modules/question_recommender.py
Labels: bug, good first issue

#12 ✨ Feature/add help option
  main.py
  modules/usage_guide.py
Labels: documentation, help wanted

#17 feat: add extion option in main menu
  main.py
Labels: good first issue, feature

#20 ✨ Feat/add sound feedback to quiz results with config toggle
  config.py
  modules/question_recommender.py
  modules/sound.py
Labels: enhancement, good first issue

#21 🐛 Bug/invalid main menu choice
  main.py
Labels: bug, good first issue
